global:
  scrape_interval: 15s

scrape_configs:
  - job_name: "lorenzo"
    scheme: https
    metrics_path: /metrics
    static_configs:
      - targets:
          - v2-9-0---lorenzo-gltxpwkfwa-ew.a.run.app