global:
  scrape_interval: 15s

scrape_configs:
  - job_name: "lorenzo"
    metrics_path: /metrics
    static_configs:
      - targets:
           - "lorenzo-82639241850.europe-west1.run.app"
    scheme: https