name: Deploy Prometheus

on:
  push:
    branches:
      - main
    paths:
      - 'monitoring/prometheus/**'


jobs:
  build-and-deploy-prometheus:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_CREDENTIALS }}

      - uses: google-github-actions/setup-gcloud@v3
        with:
          project_id: rigoberta-menchu

      - name: Build Prometheus image
        run: |
          gcloud builds submit \
            --tag europe-west1-docker.pkg.dev/rigoberta-menchu/monitoring/prometheus:latest \
            --dockerfile Dockerfile.prometheus .

      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy prometheus \
            --image europe-west1-docker.pkg.dev/rigoberta-menchu/monitoring/prometheus:latest \
            --platform managed \
            --region europe-west1 \
            --allow-unauthenticated \
            --port 9090